listening-port=3478
listening-ip=0.0.0.0
relay-ip=10.0.0.223
relay-port-range=49160-49200
external-ip=129.146.134.55/10.0.0.223
realm=echoza
server-name=EchozaTURN

lt-cred-mech
user=echoza:echoza123

fingerprint
log-file=/var/log/turnserver.log
simple-log
no-cli
